language: node_js
node_js:
  - "10.15.3"

cache:
  directories:
    - "node_modules"

services:
  - postgresql


before_script:
  - psql -c 'create database CSLC_TEST;' -U postgres
  
  
before_install:
  - "npm install"

after_success:
  - "npm run coverage"
script:
  - "npm run test"
