swagger: '2.0'
info:
  version: '1.0'
  title: Customer Service Learning Community
  description: Create a community of like minded customer service skills enthusiast to foster inspiration and innovation by leveraging the modern web.
schemes:
  - 'https'
  - 'http'
paths:
  /users:
    post:
      post:
      description: Creates a new user
      summary: Signup
      tags:
        - 'Users'
      operationId: UsersPost
      produces:
        - application/json
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: firstName
          in: formData
          required: true
          type: string
          description: 'User firstname'
        - name: lastName
          in: formData
          required: true
          type: string
          description: 'User lastname'
        - name: email
          in: formData
          required: true
          type: string
          description: 'unique email'
        - name: userName
          in: formData
          required: true
          type: string
          description: 'username'
        - name: industry
          in: formData
          required: false
          type: string
          description: 'user place of work'
        - name: age
          in: formData
          required: true
          type: integer
          format: int32
          description: 'user age'
        - name: employed
          in: formData
          required: false
          type: boolean
          description: 'employment status'
        - name: password
          in: formData
          required: true
          minLength: 8
          type: string
          description: 'user password'
        - name: confirmPassword
          in: formData
          required: true
          minLength: 8
          type: string
          description: 'user password'
      responses:
        201:
          description: 'status code'
  /users/login:
    post:
      description: Login an existing User
      summary: Signin
      tags:
        - Users
      operationId: UsersLoginPost
      produces:
        - application/json
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: email
          in: formData
          required: true
          type: string
          description: 'user registered email'
        - name: password
          in: formData
          required: true
          type: string
          description: 'user password'
      responses:
        200:
          description: 'status code'
  /user/5:
    get:
      description: Get a specific user
      summary: Get a specific user
      tags:
        - Users
      operationId: User5Get
      produces:
        - application/json
      responses:
        200:
          description: 'status code'
    put:
      description: Update an existing user details
      summary: Update a specific user information
      tags:
        - Users
      operationId: User5Put
      produces:
        - application/json
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: firstName
          in: formData
          required: false
          type: string
          description: 'User firstname'
        - name: lastName
          in: formData
          required: false
          type: string
          description: 'User lastname'
        - name: email
          in: formData
          required: false
          type: string
          description: 'unique email'
        - name: userName
          in: formData
          required: false
          type: string
          description: 'username'
        - name: industry
          in: formData
          required: false
          type: string
          description: 'user place of work'
        - name: age
          in: formData
          required: false
          type: integer
          format: int32
          description: 'user age'
        - name: employed
          in: formData
          required: false
          type: boolean
          description: 'employment status'

      responses:
        200:
          description: ''
tags:
  - name: Users
    description: User routes to signup, login, update and get specific User

externalDocs:
  description: 'Find out more about Swagger'
  url: 'http://swagger.io'
